// Desarrollo de Sistemas Distribuidos
// Grado en Ingeniería Informática
// 
// Curso 2015/2016
// 
// Borja Cañavate Bordons
// Baltasar Ruiz Hernández
// Juan José Jiménez García
//
// 3º Ingeniería del Software
// 
// Trabajo del Tema 3
// Algoritmo Valentón (Bully)
//
// PanelBully.java

package algoritmobully;

public class PanelBully extends javax.swing.JPanel {

    private Controlador controlador;
    
    /**
     * Creates new form PanelBully
     */
    public PanelBully() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        process0Panel = new javax.swing.JPanel();
        process0Title = new javax.swing.JLabel();
        process1Panel = new javax.swing.JPanel();
        process1Title = new javax.swing.JLabel();
        process4Panel = new javax.swing.JPanel();
        process4Title = new javax.swing.JLabel();
        process2Panel = new javax.swing.JPanel();
        process2Title = new javax.swing.JLabel();
        process3Panel = new javax.swing.JPanel();
        process3Title = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        colorLegend = new javax.swing.JLabel();
        stopProcess0 = new javax.swing.JButton();
        stopProcess1 = new javax.swing.JButton();
        stopProcess2 = new javax.swing.JButton();
        stopProcess3 = new javax.swing.JButton();
        StopProcess4 = new javax.swing.JButton();
        description2 = new javax.swing.JLabel();
        yellowPanel = new javax.swing.JPanel();
        greenPanel = new javax.swing.JPanel();
        redPanel = new javax.swing.JPanel();
        purplePanel = new javax.swing.JPanel();
        bluePanel = new javax.swing.JPanel();
        bossText = new javax.swing.JLabel();
        failedBossText = new javax.swing.JLabel();
        candidateText = new javax.swing.JLabel();
        startSelectionPanel = new javax.swing.JLabel();
        normalText = new javax.swing.JLabel();

        process0Panel.setBackground(new java.awt.Color(0, 204, 0));
        process0Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        process0Title.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        process0Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        process0Title.setText("Proceso 0");

        javax.swing.GroupLayout process0PanelLayout = new javax.swing.GroupLayout(process0Panel);
        process0Panel.setLayout(process0PanelLayout);
        process0PanelLayout.setHorizontalGroup(
            process0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process0PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process0Title, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        process0PanelLayout.setVerticalGroup(
            process0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process0PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process0Title, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        process1Panel.setBackground(new java.awt.Color(0, 204, 0));
        process1Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        process1Title.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        process1Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        process1Title.setText("Proceso 1");

        javax.swing.GroupLayout process1PanelLayout = new javax.swing.GroupLayout(process1Panel);
        process1Panel.setLayout(process1PanelLayout);
        process1PanelLayout.setHorizontalGroup(
            process1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process1Title, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        process1PanelLayout.setVerticalGroup(
            process1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process1Title, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        process4Panel.setBackground(new java.awt.Color(204, 102, 255));
        process4Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        process4Title.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        process4Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        process4Title.setText("Proceso 4");

        javax.swing.GroupLayout process4PanelLayout = new javax.swing.GroupLayout(process4Panel);
        process4Panel.setLayout(process4PanelLayout);
        process4PanelLayout.setHorizontalGroup(
            process4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process4Title, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        process4PanelLayout.setVerticalGroup(
            process4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process4Title, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        process2Panel.setBackground(new java.awt.Color(0, 204, 0));
        process2Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        process2Title.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        process2Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        process2Title.setText("Proceso 2");

        javax.swing.GroupLayout process2PanelLayout = new javax.swing.GroupLayout(process2Panel);
        process2Panel.setLayout(process2PanelLayout);
        process2PanelLayout.setHorizontalGroup(
            process2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process2Title, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        process2PanelLayout.setVerticalGroup(
            process2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process2Title, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        process3Panel.setBackground(new java.awt.Color(0, 204, 0));
        process3Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        process3Title.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        process3Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        process3Title.setText("Proceso 3");

        javax.swing.GroupLayout process3PanelLayout = new javax.swing.GroupLayout(process3Panel);
        process3Panel.setLayout(process3PanelLayout);
        process3PanelLayout.setHorizontalGroup(
            process3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process3Title, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        process3PanelLayout.setVerticalGroup(
            process3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(process3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(process3Title, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        title.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Algoritmo Valentón");

        description1.setFont(new java.awt.Font("Liberation Sans", 0, 11)); // NOI18N
        description1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description1.setText("Pulse en los botones de la parte inferior para detener el proceso deseado ");

        colorLegend.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        colorLegend.setText("Leyenda de colores:");

        stopProcess0.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        stopProcess0.setText("Detener proceso 0");
        stopProcess0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopProcess0ActionPerformed(evt);
            }
        });

        stopProcess1.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        stopProcess1.setText("Detener proceso 1");
        stopProcess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopProcess1ActionPerformed(evt);
            }
        });

        stopProcess2.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        stopProcess2.setText("Detener proceso 2");
        stopProcess2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopProcess2ActionPerformed(evt);
            }
        });

        stopProcess3.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        stopProcess3.setText("Detener proceso 3");
        stopProcess3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopProcess3ActionPerformed(evt);
            }
        });

        StopProcess4.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        StopProcess4.setText("Detener proceso 4");
        StopProcess4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopProcess4ActionPerformed(evt);
            }
        });

        description2.setFont(new java.awt.Font("Liberation Sans", 0, 11)); // NOI18N
        description2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description2.setText("y observar cómo se realiza el proceso de selección de nuevo candidato.");

        yellowPanel.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout yellowPanelLayout = new javax.swing.GroupLayout(yellowPanel);
        yellowPanel.setLayout(yellowPanelLayout);
        yellowPanelLayout.setHorizontalGroup(
            yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        yellowPanelLayout.setVerticalGroup(
            yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        greenPanel.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout greenPanelLayout = new javax.swing.GroupLayout(greenPanel);
        greenPanel.setLayout(greenPanelLayout);
        greenPanelLayout.setHorizontalGroup(
            greenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        greenPanelLayout.setVerticalGroup(
            greenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        redPanel.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout redPanelLayout = new javax.swing.GroupLayout(redPanel);
        redPanel.setLayout(redPanelLayout);
        redPanelLayout.setHorizontalGroup(
            redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        redPanelLayout.setVerticalGroup(
            redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        purplePanel.setBackground(new java.awt.Color(204, 102, 255));

        javax.swing.GroupLayout purplePanelLayout = new javax.swing.GroupLayout(purplePanel);
        purplePanel.setLayout(purplePanelLayout);
        purplePanelLayout.setHorizontalGroup(
            purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        purplePanelLayout.setVerticalGroup(
            purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bluePanel.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bossText.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        bossText.setText("Proceso jefe");

        failedBossText.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        failedBossText.setText("Proceso detenido");

        candidateText.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        candidateText.setText("Proceso candidato");

        startSelectionPanel.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        startSelectionPanel.setText("Proceso que inicia elecciones");

        normalText.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        normalText.setText("Proceso normal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(description1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorLegend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(description2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stopProcess0)
                        .addGap(18, 18, 18)
                        .addComponent(stopProcess1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stopProcess2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stopProcess3)
                        .addGap(18, 18, 18)
                        .addComponent(StopProcess4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(purplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bossText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(redPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(failedBossText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(candidateText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yellowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startSelectionPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(normalText)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(process0Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(process2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(process3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(process1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(process4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description1)
                .addGap(1, 1, 1)
                .addComponent(description2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorLegend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bossText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purplePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(redPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(normalText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(failedBossText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bluePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(candidateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yellowPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(process0Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(process1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(process4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(process2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(process3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopProcess0)
                    .addComponent(stopProcess1)
                    .addComponent(stopProcess2)
                    .addComponent(stopProcess3)
                    .addComponent(StopProcess4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stopProcess0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopProcess0ActionPerformed
        this.controlador.pararProceso(0);
    }//GEN-LAST:event_stopProcess0ActionPerformed

    private void stopProcess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopProcess1ActionPerformed
        this.controlador.pararProceso(1);
    }//GEN-LAST:event_stopProcess1ActionPerformed

    private void stopProcess2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopProcess2ActionPerformed
        this.controlador.pararProceso(2);
    }//GEN-LAST:event_stopProcess2ActionPerformed

    private void stopProcess3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopProcess3ActionPerformed
        this.controlador.pararProceso(3);
    }//GEN-LAST:event_stopProcess3ActionPerformed

    private void StopProcess4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopProcess4ActionPerformed
        this.controlador.pararProceso(4);
    }//GEN-LAST:event_StopProcess4ActionPerformed

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public void actualizarPaneles() {
        // Actualizar panel del proceso 0
        if(this.controlador.getProcesoConID(0).getEstado() == Proceso.ERROR) {
            process0Panel.setBackground(new java.awt.Color(255, 51, 51));
        }
        else if (this.controlador.getProcesoConID(0).getJefe() == this.controlador.getProcesoConID(0).getIdentificador()) {
            process0Panel.setBackground(new java.awt.Color(204, 102, 255));
        }
        else if (this.controlador.getProcesoConID(0).heDetectadoError()) {
            process0Panel.setBackground(new java.awt.Color(255, 255, 0));
        }
        else if (this.controlador.getProcesoConID(0).soyCandidato()) {
            process0Panel.setBackground(new java.awt.Color(51, 153, 255));
        }
        else {
            process0Panel.setBackground(new java.awt.Color(0, 204, 0));
        }
        
        // Actualizar panel del proceso 1
        if(this.controlador.getProcesoConID(1).getEstado() == Proceso.ERROR) {
            process1Panel.setBackground(new java.awt.Color(255, 51, 51));
        }
        else if (this.controlador.getProcesoConID(1).getJefe() == this.controlador.getProcesoConID(1).getIdentificador()) {
            process1Panel.setBackground(new java.awt.Color(204, 102, 255));
        }
        else if (this.controlador.getProcesoConID(1).heDetectadoError()) {
            process1Panel.setBackground(new java.awt.Color(255, 255, 0));
        }
        else if (this.controlador.getProcesoConID(1).soyCandidato()) {
            process1Panel.setBackground(new java.awt.Color(51, 153, 255));
        }
        else {
            process1Panel.setBackground(new java.awt.Color(0, 204, 0));
        }
        
        // Actualizar panel del proceso 2
        if(this.controlador.getProcesoConID(2).getEstado() == Proceso.ERROR) {
            process2Panel.setBackground(new java.awt.Color(255, 51, 51));
        }
        else if (this.controlador.getProcesoConID(2).getJefe() == this.controlador.getProcesoConID(2).getIdentificador()) {
            process2Panel.setBackground(new java.awt.Color(204, 102, 255));
        }
        else if (this.controlador.getProcesoConID(2).heDetectadoError()) {
            process2Panel.setBackground(new java.awt.Color(255, 255, 0));
        }
        else if (this.controlador.getProcesoConID(2).soyCandidato()) {
            process2Panel.setBackground(new java.awt.Color(51, 153, 255));
        }
        else {
            process2Panel.setBackground(new java.awt.Color(0, 204, 0));
        }
        
        // Actualizar panel del proceso 3
        if(this.controlador.getProcesoConID(3).getEstado() == Proceso.ERROR) {
            process3Panel.setBackground(new java.awt.Color(255, 51, 51));
        }
        else if (this.controlador.getProcesoConID(3).getJefe() == this.controlador.getProcesoConID(3).getIdentificador()) {
            process3Panel.setBackground(new java.awt.Color(204, 102, 255));
        }
        else if (this.controlador.getProcesoConID(3).heDetectadoError()) {
            process3Panel.setBackground(new java.awt.Color(255, 255, 0));
        }
        else if (this.controlador.getProcesoConID(3).soyCandidato()) {
            process3Panel.setBackground(new java.awt.Color(51, 153, 255));
        }
        else {
            process3Panel.setBackground(new java.awt.Color(0, 204, 0));
        }
        
        // Actualizar panel del proceso 4
        if(this.controlador.getProcesoConID(4).getEstado() == Proceso.ERROR) {
            process4Panel.setBackground(new java.awt.Color(255, 51, 51));
        }
        else if (this.controlador.getProcesoConID(0).getJefe() == this.controlador.getProcesoConID(4).getIdentificador()) {
            process4Panel.setBackground(new java.awt.Color(204, 102, 255));
        }
        else if (this.controlador.getProcesoConID(4).heDetectadoError()) {
            process4Panel.setBackground(new java.awt.Color(255, 255, 0));
        }
        else if (this.controlador.getProcesoConID(4).soyCandidato()) {
            process4Panel.setBackground(new java.awt.Color(51, 153, 255));
        }
        else {
            process4Panel.setBackground(new java.awt.Color(0, 204, 0));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StopProcess4;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JLabel bossText;
    private javax.swing.JLabel candidateText;
    private javax.swing.JLabel colorLegend;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel failedBossText;
    private javax.swing.JPanel greenPanel;
    private javax.swing.JLabel normalText;
    private javax.swing.JPanel process0Panel;
    private javax.swing.JLabel process0Title;
    private javax.swing.JPanel process1Panel;
    private javax.swing.JLabel process1Title;
    private javax.swing.JPanel process2Panel;
    private javax.swing.JLabel process2Title;
    private javax.swing.JPanel process3Panel;
    private javax.swing.JLabel process3Title;
    private javax.swing.JPanel process4Panel;
    private javax.swing.JLabel process4Title;
    private javax.swing.JPanel purplePanel;
    private javax.swing.JPanel redPanel;
    private javax.swing.JLabel startSelectionPanel;
    private javax.swing.JButton stopProcess0;
    private javax.swing.JButton stopProcess1;
    private javax.swing.JButton stopProcess2;
    private javax.swing.JButton stopProcess3;
    private javax.swing.JLabel title;
    private javax.swing.JPanel yellowPanel;
    // End of variables declaration//GEN-END:variables
}
